export const PERSISTENT_MEMORY_CHAT_APP_ID = "Persistent Memory";
export const REACT_CHAT_APP_ID = "ReAct";
export const AGENTIC_RAG_CHAT_APP_ID = "Agentic RAG";
export const AI_SCHOOL_AGENT_CHAT_APP_ID = "AI School Chat";
export const JWT_AGENT_CHAT_APP_ID = "JWT Agent";
export const REMOTE_AGENT_CHAT_APP_ID = "Remote Agent";
export const KALYGO_AGENT_CHAT_APP_ID = "Kalygo Agent";
export const AGENT_CHAT_APP_ID = "Agent Chat";
export const LOCAL_AGENT_CHAT_APP_ID = "Local Agent";
